### ISSUE TITLE
[Refactoring] Remove obsolete final modifier from parameters and local variables

### ISSUE THREAD

**Issue by Riggs333** [jparams/to-string-verifier#11]
I noticed the use of the `final` modifier for every(?) method parameter and local variables.
This is almost unnecessary and clutters the codes making in less readable, in my opinion.
Here is some reference about the use of final in those cases: https://www.javaspecialists.eu/archive/Issue207.html

Consider removing the use of `final` unless there is a valid reason to keep it.
I know this change will touch nearly every file. But would be a huge cleanup for the whole codebase. :-) 

What do you think?

**Comment by jparams** [comment]
Thanks for your feedback. Whilst I don’t feel too strongly about this either way, I really do think this comes down to people’s opinions. I have seen this argued from both sides quite convincingly. One side saying its unnecessary clutter and the other side saying its a useful markup. Personally, I am so used to seeing and writing these finals, it really doesn’t feel like clutter to me.

In terms of contribution, I have not written a contribution guide because we all have our preferred way of writing code, as long as the code is clean and its well tested it will get merged in. I don’t mind if people raise PRs with or without finals, or with slightly different formatting etc.

I will keep this issue open and if more contributors come on-board and feel the same as you, I am happy to go ahead and update the entire code base. 

—

Contributors should feel free to drop their opinions in the comments regarding this.
